[package]
name = "ets2-tool"
version = "0.9.8"
description = "Save-Edit Tool CN for ETS2"
authors = ["xLieferant"]
edition = "2024"
license = "MIT"
default-run = "ets2-tool"

[lib]
name = "ets2_tool_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }

[dependencies]
tauri = { version = "2.9.5", features = [] }

# Tauri Plugins
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"

# Core
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.148"
dirs = "6.0.0"
once_cell = "1.19"
reqwest = { version = "0.13.4", features = ["blocking", "json"] }
serde_urlencoded = "0.7"


# ETS2 / Tooling
decrypt_truck = "1.3.4"
walkdir = "2.5.0"
regex = "1.12.2"


# Utility
log = "0.4.29"
chrono = "0.4"
anyhow = "1.0"
uuid = { version = "1.19.0", features = ["v4"] }
zip = "7.0.0"
rust-i18n = "3.1.5"
fs_extra = "1.3.0"
base64 = "0.22"
rusqlite = { version = "0.31.0", features = ["bundled"] }
sqlx = { version = "0.8.0", features = ["sqlite", "runtime-tokio-rustls", "macros", "chrono", "uuid"] }
sha2 = "0.10.9"
windows-sys = { version = "0.59.0", features = ["Win32_Foundation", "Win32_Security", "Win32_System_Memory", "Win32_Storage_FileSystem"] }
argon2 = "0.5.3"
rand_core = { version = "0.6.4", features = ["getrandom"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"
scs-sdk-telemetry = { version = "1.2.0", features = ["json"] }
